kit:
  name: "PetClinic"
  link: https://github.com/qubell/starter-java-web
  applications:
    - name: "PetClinic"
      manifest: https://raw.github.com/qubell-bazaar/starter-java-web/2.0-39p/starter-java-web.yml
    - name: "Database"
      manifest: https://raw.github.com/qubell-bazaar/component-mysql-dev/2.0-36p/component-mysql-dev.yml
    - name: "Load Balancer"
      manifest: https://raw.github.com/qubell-bazaar/component-haproxy/2.2-39p/component-haproxy.yml
    - name: "Application Server"
      manifest: https://raw.github.com/qubell-bazaar/component-tomcat-dev/2.3-39p/component-tomcat-dev.yml
    - name: "Builder"
      manifest: https://raw.github.com/qubell-bazaar/component-maven/1.1-38p/component-maven.yml
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      This application requires the following items to be configured in your environment:
        * Amazon EC2 or Rackspace CloudServers account;
        * Ports 80 and 8080 open on the ﬁrewall.
      Please refer to the Getting Started for step-by-step instructions on how to configure your environment.
